language: node_js
node_js:
  - 'node'
cache: npm

jobs:
  include:
    - stage: install
      script: npm install
    - stage: coverage
      script:
        - npm run test:unit:coverage
        - npm run send-coverage
#    - stage: validate-version
#      before_script:
#        - chmod +x scripts/validate-version.js
#      script:
#        - node scripts/validate-version.js

#stages:
#  - name: install
#    if: (type = pull_request)
#  - name: coverage
#    if: (type = pull_request)
