language: node_js
node_js:
- node
cache: npm
jobs:
  include:
  - stage: install
    script: yarn install
  - stage: coverage
    script:
    - npm run test:unit:coverage
    - npm run send-coverage
  - stage: version
    before_script:
    - chmod +x .travis/validate-version.js
    script:
    - node .travis/validate-version.js
  - stage: deploy-npm
    script:
    - yarn install
    deploy:
      provider: npm
      email: "$ENV_EMAIL"
      api_key:
        secure: "$ENV_NPM_API_KEY"
      on:
        repo: dannyYassine/vuex-objectify
      skip_cleanup: 'true'
stages:
- name: install
  if: "(type = pull_request)"
- name: coverage
  if: "(type = pull_request)"
- name: version
  if: "(type = pull_request AND branch = master) OR (branch = master)"
- name: deploy-npm
  if: "(branch = master) AND (type = push)"
