language: node_js
node_js:
- node
cache: npm
jobs:
  include:
  - stage: install
    script: yarn install
  - stage: coverage
    script:
    - npm run test:unit:coverage
    - npm run send-coverage
  - stage: version
    before_script:
    - chmod +x .travis/validate-version.js
    script:
    - node .travis/validate-version.js
  - stage: deploy-npm
    script:
    - yarn install
    deploy:
      provider: npm
      email: $ENV_EMAIL
      api_key:
        secure: eWd3B9Pd3K5eIN54OelPbswOHI/bj8sfjB4Mbum4AZnLQdvKIFBD0bPoka65UKhwza141Nb0x842QFxxOj1k3I8k3Rqj8w75GHUJLGAP9wjS6XUf0lgIaDtrUCwg9cE9AjVVL0v9rxQ+SHFoDgyRwFJUbtZ47LORpbEMXnQOEXajXElyJIVf+b4q31q8hT6GAcoEA7d5+3PCAZvXyomQSzXP4GV30n0iN9496g3aIp6wq8rEsfevR+M7iNB1bv4u8Y4NSS7OyN6f9Ye6pNWJ+V+9qnZnTtvQzDC2yKiCnBCwzSHOgL3B/CtY4II5imexZ4JNaciJaq1WpuAYJgvLgSyhyeqbjMCivrb4RpoqERnCjIOalac8z4fK6Sn21y5JekL7GQZpzoAVQ19Mc+2b2wbLLWagFSNgs8DpX7JNXh8pVf6SzFw+pOlINmJ/5nw3lWSCO8lUKW4wii0k3tM1TaMo3x4v9+cO9g0urMqkJe62w3+yFLoGh/jdkIZiqk5vQuSS1QTLEuW7pNKiwsD0om3W5puO3U7wZKU3eRBpOGDQpfSHt0+S+F1AlurtIVwXlZkHfQayzzJsAEPqZLqDKVaoyOyA5X5DQ1DIOT94J4hYOGnjfj97N7zmZmAzQoLeEoNeOUPF5C1zsVbsVTVAfInGmJZuq4DYACysQJsleMU=
      skip_cleanup: 'true'
stages:
- name: install
  if: "(type = pull_request)"
- name: coverage
  if: "(type = pull_request)"
- name: version
  if: "(type = pull_request AND branch = master) OR (branch = master)"
- name: deploy-npm
  if: "(branch = master) AND (type = push)"
